version: "3"
services:
  nats:
    image: nats:2.9.0
    command: "-js -c /nats.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "7422:7422"
    volumes:
      - ./nats.conf:/nats.conf
      - ./certs:/certs
